

export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';

export const ADD_ITEM_CAROUSEL = 'ADD_ITEM_CAROUSEL';
export const DELETE_ITEM_CAROUSEL = 'DELETE_ITEM_CAROUSEL';
export const UNDO_ITEM_CAROUSEL = 'UNDO_ITEM_CAROUSEL';
export const REDO_ITEM_CAROUSEL = 'REDO_ITEM_CAROUSEL';
export const RESET_ITEM_CAROUSEL = 'RESET_ITEM_CAROUSEL';

export const ADD_ITEMROW = 'ADD_ITEMROW';
export const DELETE_ITEMROW = 'DELETE_ITEMROW';
export const UNDO_ITEMROW = 'UNDO_ITEMROW';
export const REDO_ITEMROW = 'REDO_ITEMROW';
export const RESET_ITEMROW = 'RESET_ITEMROW';
export const DELETE_EMPTY_ITEMROW = 'DELETE_EMPTY_ITEMROW';

export const ADD_USER_SIGNAL =   'ADD_USER_SIGNAL';