

export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';

export const ADD_IMAGE_CAROUSEL = 'ADD_IMAGE_CAROUSEL';
export const DELETE_IMAGE_CAROUSEL = 'DELETE_IMAGE_CAROUSEL';
export const UNDO_IMAGE_CAROUSEL = 'UNDO_IMAGE_CAROUSEL';
export const REDO_IMAGE_CAROUSEL = 'REDO_IMAGE_CAROUSEL';

export const ADD_USER_SIGNAL =   'ADD_USER_SIGNAL';